spring.datasource.url=jdbc:mysql://localhost:3306/billingSoftware
spring.datasource.username=root
spring.datasource.password=Qaz@2212


spring.jpa.hibernate.ddl-auto=update
server.servlet.context-path=/api/v1.0

cloudinary.cloud-name=billingsoftware
cloudinary.api-key=354146592479366
cloudinary.api-secret=cYOgBXtUAhP6qUeLpuyc9xX4l0s

jwt.secret.key=liduu84e12423ueNWWIGdhsbyfu1qwertgfds3dSWS@WWw

rezorpay.api-key=rzp_test_Rr4wCLS2HwDUWq
rezorpay.secret-key=2MiqJRrmkmc73oSPlKJZ0EFb

