spring.datasource.url=YOUR_DB_URL
spring.datasource.username=YOUR_DB_USERNAME
spring.datasource.password=YOUR_DB_PASSWORD

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

server.servlet.context-path=/api/v1.0

cloudinary.cloud-name=YOUR_CLOUDINARY_CLOUD_NAME
cloudinary.api-key=YOUR_CLOUDINARY_API_KEY
cloudinary.api-secret=YOUR_CLOUDINARY_API_SECRET

jwt.secret.key=YOUR_JWT_SECRET_KEY

razorpay.api-key=YOUR_RAZORPAY_API_KEY
razorpay.secret-key=YOUR_RAZORPAY_SECRET_KEY
